### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/screen.rs:272:65

### ISSUE THREAD

**Issue by Rohanator2314** [Username-08/lightnovel-cli#3]
error when opening any novel:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/screen.rs:272:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Username-08** [comment]
Hi, unfortunately freewebnovels.com has started using cloudfare captcha recently, so this problem is occurring.
I am trying to find a way to fix this

**Comment by OsmanFrat** [comment]
its not working now, isn't it? :(
